### PR TITLE
Fallback to allowed_profiles to validate securityContext.

### LINKED ISSUE #6: Seccomp policy fail when Kubernetes populate `securityContext` automatically.
This is a spin-off of the #4. 

@chrisns reported that when using the following configuration:

```bash
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: seccomp
spec:
  module: registry://ghcr.io/kubewarden/policies/seccomp-psp:v0.1.0
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
      operations:
      - CREATE
      - UPDATE
  mutating: false
  settings:
    allowed_profiles:
      - runtime/default
EOF
```

He cannot deploy this pod:

```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-allowed
  annotations:
    container.seccomp.security.alpha.kubernetes.io/nginx: runtime/default
  labels:
    app: nginx-seccomp
spec:
  containers:
  - name: nginx
    image: nginx
EOF

Error from server: error when creating "tests/seccomp/allowed.yaml": admission webhook "seccomp.kubewarden.admission" denied the request: Resource violations: Invalid container seccomp profile types: RuntimeDefault
```

This happens due to the way the policy settings are implemented. When the users define the `allowed_profiles` settings they are saying "please, check if the annotations in the pod have these profiles" (see the code [here](https://github.com/kubewarden/seccomp-psp-policy/blob/main/src/lib.rs#L50-L69)). However, Kubernetes updates the `securityContext` automatically when these annotations are set. Which is causing this problem. A workaround for that is just to replicate the equivalent configuration in the other settings (`profile_types` and `localhost_profiles`). Something like:

```bash
kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: seccomp
spec:
  module: registry://ghcr.io/kubewarden/policies/seccomp-psp:v0.1.0
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
      operations:
      - CREATE
      - UPDATE
  mutating: false
  settings:
    allowed_profiles:
      - runtime/default
    profile_types:
      - RuntimeDefault
EOF
```

I understand that is a pain. So, I'm opening this to improve that.

### PR DESCRIPTION
**Pull request by jvanz**
When the user defines the seccomp profile using annotations, later 
Kubernetes versions will populate the securityContext field
automatically with the equivalent configuration. This can cause
rejections when the users are using the seccomp policy with no
`profile_types` and `localhost_profiles` configuration.

To mitigate this, the policy now fall-back to the `allowed_profiles`
settings when it cannot validate the securityContext configuration with
the `localhost_profiles` and `localhost_profiles` settings.

Closes #6

### CODE REVIEW

**Comment by jvanz** [comment]
@chrisns , can you test this as well? To make your life easier, I've published the OCI artifact at: ghcr.io/jvanz/policies/seccomp-psp:issue6

**Comment by chrisns** [comment]
lgtm https://github.com/appvia/psp-migration/blob/8ba56712249d36e2e2cbf6c9abc2d2a16c7f922d/tests/seccomp/kubewarden.yaml 👍  presuming i'm testing it right?

**Comment by jvanz** [comment]
> lgtm https://github.com/appvia/psp-migration/blob/8ba56712249d36e2e2cbf6c9abc2d2a16c7f922d/tests/seccomp/kubewarden.yaml +1 presuming i'm testing it right?

AFAICS, yes, you are. :-)

File: src/lib.rs [hunk 1]
```diff
@@ -68,6 +68,49 @@ fn do_validate_annotations(pod: &apicore::Pod, settings: &settings::Settings) ->
...
 
+/* Function used to check if the seccomp profile type is defined in the
+ * allowed_profiles settings
+ */
+fn allowed_profiles_has_profile_type(
+    settings: &settings::Settings,
+    seccomp_profile: &apicore::SeccompProfile,
+) -> bool {
+    // Unfortunately, we cannot store the allowed_profiles settings parsed to
+    // avoid this iteration in every evaluation.
```
Comment (flavio) [inline src/lib.rs:79]: I don't think this is going to a big performance issue, because I don't expect many security profiles to be specified. However, if that's the case, we can always build a small lookup table inside of the `validate` function. But I would definitely leave that for later

**Review by flavio — COMMENTED** [review]
Overall LGTM. I left one comment that requires action (the one inside of the README)
